server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/organization_db
    username: root
    password: alex
  jpa:
    properties:
      hibernate:
    hibernate:
      ddl-auto: update
rabbitmq:
  host: localhost
  post: 5672
  username: guest
  password: guest

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: '%p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org.springframework.web: DEBUG

my:
  test:
    message: Hello department-service. This is test message!
